### ISSUE TITLE
Tweeks to shopify project

### ISSUE THREAD

**Issue by des-des** [gazaskygeeks/digital-agency#24]
I expect this will not be more than a week of work. Mostly making tweeks to a shopify site.

[2018-04-19 Programming requirements (RH reviewed).docx](https://github.com/gazaskygeeks/digital-agency/files/1945817/2018-04-19.Programming.requirements.RH.reviewed.docx)

I am looking for someone to take lead trying to understand that document, scoping, then meeting with me and the client next week.

@gazaskygeeks/facg1 @gazaskygeeks/facg2 

Post your gh handles below or email me if you are interested

**Comment by mohanagy** [comment]
@mohanagy

**Comment by muhmushtaha** [comment]
@muhmushtaha

**Comment by des-des** [comment]
This did not go ahead
